# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Create new bond (testnet)

on:
  push:
    branches:
      - main

  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook_testnet

env:
  ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_URL: ${{ secrets.ETHERSCAN_URL }}
  TOKEN_MULTISIG: ${{ secrets.TOKEN_MULTISIG }}
  ROUTER_ADDRESS: ${{ '' }}
  NAME: ${{ '' }}
  SYMBOL: ${{ '' }}
  AMOUNT: ${{ '' }}
  TERMS: ${{ '' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: testnet
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: "Run"
        run: |
          npm install
          npx hardhat run scripts/deploy-token.ts --network goerli
