# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Create new bond (testnet)

on:
  push:
    branches:
      - main

  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook_testnet

env:
  ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_URL: ${{ secrets.ETHERSCAN_URL }}
  TOKEN_MULTISIG: ${{ secrets.TOKEN_MULTISIG }}
  ID: ${{ github.event.client_payload.id }}
  ROUTER_ADDRESS: ${{ github.event.client_payload.routerAddress }}
  NAME: ${{ github.event.client_payload.name }}
  SYMBOL: ${{ github.event.client_payload.symbol }}
  AMOUNT: ${{ github.event.client_payload.amount }}
  TERMS: ${{ github.event.client_payload.terms }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: testnet
    steps:
      - uses: actions/checkout@v3

      - name: "Test"
        shell: pwsh
        run: >
          Write-Host "Name: ${{ env.NAME }}"

      - name: "Run"
        if: ${{ false }}
        run: |
          npm install
          npx hardhat run scripts/deploy-token.ts --network goerli
