# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Create new bond (testnet)

on:
  repository_dispatch:
    types:
      - webhook_testnet

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_URL: ${{ secrets.ETHERSCAN_URL }}
  TOKEN_MULTISIG: ${{ secrets.TOKEN_MULTISIG }}
  ID: ${{ github.event.client_payload.id }}
  ROUTER_ADDRESS: ${{ github.event.client_payload.routerAddress }}
  NAME: ${{ github.event.client_payload.name }}
  SYMBOL: ${{ github.event.client_payload.symbol }}
  AMOUNT: ${{ github.event.client_payload.amount }}
  TERMS: ${{ github.event.client_payload.terms }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: testnet
    steps:
      - uses: actions/checkout@v3

      - name: "Show info"
        shell: pwsh
        run: |
          Write-Host "Id: ${{ env.ID }}"
          Write-Host "RouterAddress: ${{ env.ROUTER_ADDRESS }}"
          Write-Host "Name: ${{ env.NAME }}"
          Write-Host "Symbol: ${{ env.SYMBOL }}"
          Write-Host "Amount: ${{ env.AMOUNT }}"
          Write-Host "Terms: ${{ env.TERMS }}"

      - name: "Run"
        run: |
          npm install
          npx hardhat run scripts/deploy-token.ts --network goerli
